env: "local" # local, dev, prod etc...
storage_path: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  admin_pass: adminaccess